{{- if and .Values.enabledCollectors (eq (.Values.deploymentMode | default "daemonset") "daemonset") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sealos-state-metrics.fullname" . }}
  labels:
    {{- include "sealos-state-metrics.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.maxUnavailable | quote }}
  selector:
    matchLabels:
      {{- include "sealos-state-metrics.selectorLabels" . | nindent 6 }}
  template:
    {{- include "sealos-state-metrics.podTemplate" . | nindent 4 }}
{{- end }}
